# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: ihvoitka
    role: Maintain
  - member: pedramr
    role: Maintain
  - member: pyoussef
    role: Admin
  - member: rynowak
    role: Maintain
  - member: stephenngo
    role: Maintain
